### ISSUE TITLE
Cleaner executable name

### ISSUE THREAD

**Issue by merwok** [dpmcmlxxvi/clistats#3]
Hello!  Thanks for this program, I was checking out qstats and ministat and this one seems more useful.

I was surprised to see that the compiled executable is named `clistats.exe`; this seems very uncommon for a unix program.  Could this become `clistats`?

In addition, it should be added to .gitignore.

**Comment by dpmcmlxxvi** [comment]
Sure thing. Easy enough fix. Will look into it when I get a few free cycles.

**Comment by merwok** [comment]
Sent a PR!  The examples in README already used `clistats` so things seem good.
